### ISSUE TITLE
CDM schema name is hard-coded in cohort generation SQL scripts

### ISSUE THREAD

**Issue by ablack3** [clinicalml/omop-learn#4]
**Description of issue**

The name of the cdm schema will be different in each environment but it is hard coded as 'cdm' in the cohort generation SQL scripts.  One example is [here.](https://github.com/clinicalml/omop-learn/blob/33a4658bc6ffe5ad08992185ffefbe8d9f667a2f/sql/Cohorts/gen_EOL_cohort.sql#L18)

**Proposed solution**

Add a parameter to the SQL files for the name of the cdm schema and replace all occurrences of the cdm schema name with the parameter.

**Comment by justinlimkz** [comment]
Hey Adam, thanks for pointing this out - we're on it!

**Comment by justinlimkz** [comment]
I've updated the cohort queries to use the CDM schema specified in config.py, which is what the feature queries were doing. It's passed in through [this line](https://github.com/clinicalml/omop-learn/blob/5c1c785c639aded51f0868dbe0e4ffa0c90b5735/Generators/CohortGenerator.py#L67) in Generators/CohortGenerator.py.

The cohort obtained using gen_EOL_cohort.sql is the same before and after the change.
